intra-exp:
  LN_foraging:
    - src: collected-data
      dest: robot-counts
      cols:
        - walking
        - resting
      title: 'Robot Counts'
      legend:
        - 'Walking'
        - 'Resting'

      xlabel: 'Time'
      ylabel: '\# Robots'
      type: 'stacked_line'

    - src: collected-data
      dest: food-counts
      cols:
        - collected_food
      title: 'Collected Food Counts'
      legend:
        - ''

      xlabel: 'Time'
      ylabel: '\# Items'
      type: 'stacked_line'

    - src: collected-data
      dest: swarm-energy
      cols:
        - energy
      title: 'Swarm Energy Over Time'
      legend:
        - ''

      xlabel: 'Time'
      type: 'stacked_line'

inter-exp:
  LN_foraging:
    - src: collected-data
      dest: robot-counts-walking
      cols:
        - walking
      title: 'Robot Walking Counts'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: robot-counts-resting
      cols:
        - resting
      title: 'Robot Resting Counts'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: food-counts
      cols:
        - collected_food
      title: 'Collected Food Counts'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: swarm-energy
      cols:
        - energy
      title: 'Swarm Energy Over Time'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: swarm-energy-summary
      col: energy
      title: 'Swarm Energy Over Time'
      type: 'summary_line'

imagize:
  - src: floor-state
    title: 'Floor State'
    type: 'heatmap'
