intra-exp:
  LN_foraging:
    - src: collected-data
      dest: robot-counts
      cols:
        - walking
        - resting
      title: 'Robot Counts'
      legend:
        - 'Walking'
        - 'Resting'

      xlabel: 'Time'
      ylabel: '\# Robots'
      type: 'stacked_line'

    - src: collected-data
      dest: food-counts
      cols:
        - collected_food
      title: 'Collected Food Counts'
      legend:
        - ''

      xlabel: 'Time'
      ylabel: '\# Items'
      type: 'stacked_line'

    - src: collected-data
      dest: swarm-energy
      cols:
        - energy
      title: 'Swarm Energy Over Time'
      legend:
        - ''

      xlabel: 'Time'
      type: 'stacked_line'

inter-exp:
  HM_foraging:
    - src: collected-data
      dest: robot-counts-walking2
      z: walking
      title: 'Robot Walking Counts'
      type: 'heatmap'

    - src: collected-data
      dest: robot-counts-resting2
      z: resting
      title: 'Robot Resting Counts'
      type: 'heatmap'

    - src: collected-data
      dest: food-counts2
      z: collected_food
      title: 'Collected Food Counts'
      type: 'heatmap'

    - src: collected-data
      dest: swarm-energy2
      z: energy
      title: 'Swarm Energy Over Time'
      type: 'heatmap'

  LN_foraging:
    - src: collected-data
      dest: robot-counts-walking
      cols:
        - walking
      title: 'Robot Walking Counts'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: robot-counts-resting
      cols:
        - resting
      title: 'Robot Resting Counts'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: food-counts
      cols:
        - collected_food
      title: 'Collected Food Counts'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: swarm-energy
      cols:
        - energy
      title: 'Swarm Energy Over Time'
      xlabel: 'Time'
      type: 'stacked_line'

    - src: collected-data
      dest: swarm-energy-summary
      col: energy
      title: 'Swarm Energy Over Time'
      type: 'summary_line'

imagize:
  - src: floor-state
    title: 'Floor State'
    type: 'heatmap'

inter-controller:
  # Food counts

  # If you are using bivariate batch criteria, use this one (the # at the end
  # is needed to trigger generation from specific heatmap in the temporal
  # sequence). See SIERRA examples.
  # - src: food-counts_10
  #   dest: cc-food-counts
  #   title: 'Collected Food Counts'
  #   label: 'A clever label with LaTeX! $P(\mathcal{N})$'
  #   include_exp: '0:'

  # If you are using univariate batch criteria, use this one.
  - src: food-counts
    dest: cc-food-counts
    type: 'comparison_line'
    title: 'Collected Food Counts'
    label: 'A clever label with LaTeX! $P(\mathcal{N})$'
    include_exp: '0:'

  # Energy

  # If you are using bivariate batch criteria, use this one (the # at the end
  # is needed to trigger generation from specific heatmap in the temporal
  # sequence). See SIERRA examples.
  # - src: swarm-energy_10
  #   type: 'heatmap'
  #   dest: cc-swarm-energy
  #   title: 'Swarm Energy'
  #   label: 'Another clever label'
  #   include_exp: '1:'

  # If you are using univariate batch criteria, use this one.
  - src: swarm-energy
    type: 'comparison_line'
    dest: cc-swarm-energy
    title: 'Swarm Energy'
    label: 'Another clever label'
    include_exp: '1:'

inter-scenario:
  # Food counts
  - src: food-counts
    dest: sc-food-counts
    type: 'comparison_line'
    title: 'Collected Food Counts'
    label: 'A clever label with LaTeX! $P(\mathcal{N})$'

  # Energy
  - src: swarm-energy
    dest: sc-swarm-energy
    type: 'comparison_line'
    title: 'Swarm Energy'
    label: 'Another clever label'
    include_exp: '1:'
