LN_foraging:
  graphs:
    - src_stem: collected-data
      dest_stem: robot-counts-walking
      col: walking
      title: 'Robot Walking Counts'
      xlabel: 'Time'

    - src_stem: collected-data
      dest_stem: robot-counts-resting
      col: resting
      title: 'Robot Resting Counts'
      xlabel: 'Time'

    - src_stem: collected-data
      dest_stem: food-counts
      col: collected_food
      title: 'Collected Food Counts'
      xlabel: 'Time'

    - src_stem: collected-data
      dest_stem: swarm-energy
      col: energy
      title: 'Swarm Energy Over Time'
      xlabel: 'Time'
