turtlebot3:
  controllers:
    - name: wander
      xml:
        tag_add:
          - [".//launch/group/[@ns='__UUID__']", 'node', "{'name': 'turtlebot3_drive','pkg': 'turtlebot3_gazebo', 'type': 'turtlebot3_drive', 'required': 'true'}"]
          - [".//launch/group/[@ns='__UUID__']", 'param', "{'name': 'cmd_vel_topic_name', 'value':'cmd_vel'}"]
