sierra:
  run:
    run_metrics_leaf: 'output'

  perf: 'perf.yaml'

rosgazebo:
  robots:
    turtlebot3:
      pkg: "turtlebot3_gazebo"
      model: "turtlebot3"
      prefix: "tb3_"
      model_variant: "burger"
