turtlebot3_real:
  xml:
    # Bringup core turtlebot + lidar sensor.
    tag_add:
      - [".//robot/group/[@ns='__UUID__']", 'include', "{'file': '$(find turtlebot3_bringup)/launch/turtlebot3_robot.launch'}"]

  controllers:
    - name: wander
      xml:
        tag_add:
          - [".//robot/group/[@ns='__UUID__']", 'node', "{'name': 'turtlebot3_drive','pkg': 'turtlebot3_gazebo', 'type': 'turtlebot3_drive', 'required': 'true'}"]
          - [".//robot/group/[@ns='__UUID__']", 'param', "{'name': 'cmd_vel_topic_name', 'value':'cmd_vel'}"]
